version: "3.3"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recon
    expose:
      - "5433"
    ports:
      - 5433:5433
    command: -p 5433
    volumes:
      - db-data:/var/lib/postgresql/data
  test-db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    expose:
      - "6433"
    ports:
      - 6433:6433
    command: -p 6433
  recon-api:
    ports:
      - 5000:5000
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api/src:/usr/src/api/src
      - /usr/src/api/node_modules
    env_file:
      - ./api/.env
    environment:
      - POSTGRES_HOST=host.docker.internal
    restart: always
    depends_on:
      - db
  recon-app:
    ports:
      - 3000:3000
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/usr/src/app/src
      - /usr/src/app/.next
    restart: always
    depends_on:
      - recon-api
volumes:
  db-data:
