version: "3.3"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=recon
    expose:
      - "5433"
    ports:
      - 5433:5433
    command: -p 5433
    volumes:
      - db-data:/var/lib/postgresql/data
  recon-api:
    ports:
      - 5000:5000
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    env_file:
      - api/.env.docker
    restart: always
    depends_on:
      - db
  recon-app:
    ports:
      - 3000:3000
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: always
    depends_on:
      - recon-api
volumes:
  db-data:
