#Azure CI pipeline 

trigger:
  branches:
    include:
    - devops/ado-pipelines
  paths:
    include:
      - api/*

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build_Push_Artifacts
   
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Ascendum ACR'
      command: 'login'
      
  - task: Docker@2
    inputs:
      containerRegistry: "Ascendum ACR'
      repository: $(Build.Repository.Name)_$(Build.SourceBranchName)_$(imageName)
      command: 'buildAndPush'
      Dockerfile: 'api/Dockerfile'
      tags: |
        $(Build.SourceVersion)
  - task: Docker@2
    inputs:
      containerRegistry: 'Ascendum ACR'
      command: 'logout'
