#Azure CI pipeline

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - api/*

jobs:
  - job: Build_Push_Artifacts

    steps:
      - task: Docker@2
        inputs:
          containerRegistry: "Ascendum ACR"
          command: "login"

      - task: Docker@2
        inputs:
          containerRegistry: "Ascendum ACR"
          repository: $(Build.Repository.Name)_$(Build.SourceBranchName)_recon-api
          command: "buildAndPush"
          Dockerfile: "api/Dockerfile"
          tags: |
            $(Build.SourceVersion)
      - task: Docker@2
        inputs:
          containerRegistry: "Ascendum ACR"
          command: "logout"
